=== zombier78/znackovaci-jazyky-konfigurace-xml/fsx.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="konfigurace_fsx">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="graphicsSettingsPreset"/>
        <xs:element type="xs:string" name="realismPreset"/>
        <xs:element type="xs:string" name="weatherPreset"/>
        <xs:element name="gameSettings">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mainSettings">
                <xs:annotation>
                  <xs:documentation>Globalni nastaveni hry</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="userObjects">
                      <xs:annotation>
                        <xs:documentation>Hlavni nastaveni</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:byte" name="airplane"/>
                          <xs:element type="xs:byte" name="helicopter"/>
                          <xs:element type="xs:byte" name="groundVehicles"/>
                          <xs:element type="xs:byte" name="boats"/>
                          <xs:element type="xs:byte" name="miscellaneous"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="defaultLocation"/>
                    <xs:element type="xs:string" name="language"/>
                    <xs:element type="xs:string" name="measureSystem"/>
                    <xs:element type="xs:byte" name="flyingTips"/>
                    <xs:element type="xs:byte" name="frameLimiter"/>
                    <xs:element type="xs:byte" name="recordFlight"/>
                    <xs:element name="multiplayerSettings">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="username"/>
                          <xs:element type="xs:string" name="password"/>
                          <xs:element type="xs:byte" name="savePassword"/>
                          <xs:element type="xs:string" name="defaultServerIp"/>
                          <xs:element type="xs:byte" name="shareCockpit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="sound">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="music"/>
                    <xs:element type="xs:byte" name="sounds"/>
                    <xs:element type="xs:byte" name="soundQuality"/>
                    <xs:element type="xs:byte" name="volume"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="display">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="menuHideDefault"/>
                    <xs:element type="xs:byte" name="infoOverspeed"/>
                    <xs:element type="xs:byte" name="infoParkingBrakes"/>
                    <xs:element type="xs:byte" name="infoPause"/>
                    <xs:element type="xs:byte" name="infoStall"/>
                    <xs:element type="xs:byte" name="fullscreen"/>
                    <xs:element type="xs:byte" name="descendGuideLine"/>
                    <xs:element name="views">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:byte" name="cockpit3d"/>
                          <xs:element type="xs:byte" name="thirdPersonViewEnable"/>
                          <xs:element type="xs:byte" name="newWindowEnable"/>
                          <xs:element type="xs:byte" name="changeWindowSizeEnable"/>
                          <xs:element type="xs:byte" name="defaultView"/>
                          <xs:element type="xs:string" name="defaultCockpitCameraPosition"/>
                          <xs:element type="xs:byte" name="cockpitMovementSpeed"/>
                          <xs:element type="xs:byte" name="showCockpitTooltips"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="controls">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="joystickEnable"/>
                    <xs:element type="xs:byte" name="mouseControlEnable"/>
                    <xs:element type="xs:string" name="defaultControls"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="atc">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="AtcVoice"/>
                    <xs:element type="xs:byte" name="showOnStart"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="graphics" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:short" name="textureMaxLoad"/>
                    <xs:element type="xs:byte" name="aircraftLightsQuality"/>
                    <xs:element type="xs:byte" name="aircraftShadows"/>
                    <xs:element type="xs:byte" name="aircraftReflections"/>
                    <xs:element type="xs:byte" name="cockpitHighRes"/>
                    <xs:element type="xs:byte" name="landingLights"/>
                    <xs:element type="xs:byte" name="aircraftSelfShadowEnable"/>
                    <xs:element type="xs:byte" name="effectsQuality"/>
                    <xs:element type="xs:byte" name="groundShadows"/>
                    <xs:element type="xs:byte" name="textureQuality"/>
                    <xs:element type="xs:byte" name="d3d10"/>
                    <xs:element type="xs:byte" name="antialiasing"/>
                    <xs:element type="xs:byte" name="anisotropic"/>
                    <xs:element type="xs:byte" name="bilinear"/>
                    <xs:element type="xs:byte" name="trilinear"/>
                    <xs:element type="xs:string" name="resolution"/>
                    <xs:element type="xs:byte" name="bloom"/>
                    <xs:element type="xs:byte" name="lensFlare"/>
                    <xs:element type="xs:byte" name="panelsQuality"/>
                    <xs:element type="xs:byte" name="cloudQuality"/>
                    <xs:element type="xs:short" name="cloudDrawDistance"/>
                    <xs:element type="xs:byte" name="cloudCoverageDensity"/>
                    <xs:element type="xs:byte" name="terrainResolution"/>
                    <xs:element type="xs:byte" name="sceneryDensity"/>
                    <xs:element type="xs:byte" name="roadVehicleDensity"/>
                    <xs:element type="xs:byte" name="boatDensity"/>
                    <xs:element type="xs:byte" name="airlineTrafficDensity"/>
                    <xs:element type="xs:byte" name="airportGroundVehiclesDensity"/>
                    <xs:element type="xs:byte" name="waterReflections"/>
                    <xs:element type="xs:byte" name="waveRippleEffect"/>
                    <xs:element type="xs:byte" name="advancedAnimations"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="preset" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="realism" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="realismLevel"/>
                    <xs:element type="xs:byte" name="crashesAllow"/>
                    <xs:element type="xs:byte" name="aircraftStressAllow"/>
                    <xs:element type="xs:byte" name="overspeedAllow"/>
                    <xs:element type="xs:byte" name="collisionsAllow"/>
                    <xs:element type="xs:byte" name="automaticMixtureEnable"/>
                    <xs:element type="xs:byte" name="autoTrim"/>
                    <xs:element type="xs:byte" name="failureManagerEnable"/>
                    <xs:element type="xs:byte" name="randomFailureEnable"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="preset" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="weather" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:byte" name="downloadRealData"/>
                    <xs:element type="xs:byte" name="turbulenceEnable"/>
                    <xs:element type="xs:byte" name="windMinKt"/>
                    <xs:element type="xs:byte" name="windMaxKt"/>
                    <xs:element type="xs:byte" name="windShearEnable"/>
                    <xs:element type="xs:byte" name="gustsMinKt"/>
                    <xs:element type="xs:byte" name="gustsMaxKt"/>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="preset" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="gameSave">
          <xs:annotation>
            <xs:documentation>Konec globálních nastavení, začátek konkrétního savu...
souřadnice jsou reálné, ale nekontroloval jsem jejich pozice vzhledem k letadlům, takže je možné, že některé letadlo se nachází na hladině oceánu</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nearAircraftPositions">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="aircraft" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="type"/>
                          <xs:element name="position">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:float" name="latitude"/>
                                <xs:element type="xs:float" name="longtitude"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:int" name="altitude"/>
                          <xs:element type="xs:short" name="speed"/>
                          <xs:element type="xs:short" name="heading"/>
                          <xs:element type="xs:byte" name="ifrRules"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="code" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== zombier78/znackovaci-jazyky-konfigurace-xml/fsx transformovany xml.xml
<?xml version="1.0" encoding="UTF-8"?>
 <?xml-stylesheet type="text/xsl" href="fsx.xslt"?>
<konfigurace_fsx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fsx.xsd">
	<graphicsSettingsPreset>Medium</graphicsSettingsPreset>
	<realismPreset>pro</realismPreset>
	<weatherPreset>windy</weatherPreset>
	<gameSettings>
	<!-- Globalni nastaveni hry-->
		<mainSettings>
			<!--Hlavni nastaveni-->
			<userObjects>
				<airplane>1</airplane>
				<helicopter>1</helicopter>
				<groundVehicles>0</groundVehicles>
				<boats>0</boats>
				<miscellaneous>0</miscellaneous>
			</userObjects>
			<defaultLocation>lkpr</defaultLocation>
			<language>en</language>
			<measureSystem>imperial</measureSystem>
			<flyingTips>0</flyingTips>
			<frameLimiter>0</frameLimiter>
			<recordFlight>1</recordFlight>
			<multiplayerSettings>
				<username>zombier78</username>
				<password>null</password>
				<savePassword>0</savePassword>
				<defaultServerIp>192.147.0.5.4</defaultServerIp>
				<shareCockpit>1</shareCockpit>
			</multiplayerSettings>
		</mainSettings>
		<sound>
			<music>0</music>
			<sounds>0</sounds>
			<soundQuality>3</soundQuality>
			<volume>10</volume>
		</sound>
		<display>
			<menuHideDefault>1</menuHideDefault>
			<infoOverspeed>1</infoOverspeed>
			<infoParkingBrakes>1</infoParkingBrakes>
			<infoPause>1</infoPause>
			<infoStall>1</infoStall>
			<fullscreen>1</fullscreen>
			<descendGuideLine>0</descendGuideLine>
			<views>
				<cockpit3d>1</cockpit3d>
				<thirdPersonViewEnable>0</thirdPersonViewEnable>
				<newWindowEnable>1</newWindowEnable>
				<changeWindowSizeEnable>1</changeWindowSizeEnable>
				<defaultView>2</defaultView>
				<defaultCockpitCameraPosition>50,35,20</defaultCockpitCameraPosition>
				<cockpitMovementSpeed>35</cockpitMovementSpeed>
				<showCockpitTooltips>0</showCockpitTooltips>
			</views>
		</display>
		<controls>
			<joystickEnable>1</joystickEnable>
			<mouseControlEnable>0</mouseControlEnable>
			<defaultControls>keyboard</defaultControls>
		</controls>
		<atc>
			<AtcVoice>male1</AtcVoice>
			<showOnStart>0</showOnStart>
		</atc>
		<graphics preset="ultra_Low">
			<textureMaxLoad>1024</textureMaxLoad>
			<aircraftLightsQuality>1</aircraftLightsQuality>
			<aircraftShadows>0</aircraftShadows>
			<aircraftReflections>0</aircraftReflections>
			<cockpitHighRes>1</cockpitHighRes>
			<landingLights>0</landingLights>
			<aircraftSelfShadowEnable>0</aircraftSelfShadowEnable>
			<effectsQuality>1</effectsQuality>
			<groundShadows>0</groundShadows>
			<textureQuality>1</textureQuality>
			<d3d10>0</d3d10>
			<antialiasing>0</antialiasing>
			<anisotropic>0</anisotropic>
			<bilinear>0</bilinear>
			<trilinear>1</trilinear>
			<resolution>800x600</resolution>
			<bloom>0</bloom>
			<lensFlare>0</lensFlare>
			<panelsQuality>1</panelsQuality>
			<cloudQuality>1</cloudQuality>
			<cloudDrawDistance>50</cloudDrawDistance>
			<cloudCoverageDensity>10</cloudCoverageDensity>
			<terrainResolution>20</terrainResolution>
			<sceneryDensity>10</sceneryDensity>
			<roadVehicleDensity>10</roadVehicleDensity>
			<boatDensity>10</boatDensity>
			<airlineTrafficDensity>30</airlineTrafficDensity>
			<airportGroundVehiclesDensity>30</airportGroundVehiclesDensity>
			<waterReflections>0</waterReflections>
			<waveRippleEffect>0</waveRippleEffect>
			<advancedAnimations>0</advancedAnimations>
		</graphics>
			<graphics preset="low">
			<textureMaxLoad>1024</textureMaxLoad>
			<aircraftLightsQuality>2</aircraftLightsQuality>
			<aircraftShadows>1</aircraftShadows>
			<aircraftReflections>0</aircraftReflections>
			<cockpitHighRes>1</cockpitHighRes>
			<landingLights>1</landingLights>
			<aircraftSelfShadowEnable>0</aircraftSelfShadowEnable>
			<effectsQuality>1</effectsQuality>
			<groundShadows>0</groundShadows>
			<textureQuality>2</textureQuality>
			<d3d10>0</d3d10>
			<antialiasing>0</antialiasing>
			<anisotropic>1</anisotropic>
			<bilinear>0</bilinear>
			<trilinear>0</trilinear>
			<resolution>1366x768</resolution>
			<bloom>0</bloom>
			<lensFlare>0</lensFlare>
			<panelsQuality>2</panelsQuality>
			<cloudQuality>1</cloudQuality>
			<cloudDrawDistance>80</cloudDrawDistance>
			<cloudCoverageDensity>40</cloudCoverageDensity>
			<terrainResolution>20</terrainResolution>
			<sceneryDensity>20</sceneryDensity>
			<roadVehicleDensity>20</roadVehicleDensity>
			<boatDensity>20</boatDensity>
			<airlineTrafficDensity>20</airlineTrafficDensity>
			<airportGroundVehiclesDensity>20</airportGroundVehiclesDensity>
			<waterReflections>0</waterReflections>
			<waveRippleEffect>0</waveRippleEffect>
			<advancedAnimations>0</advancedAnimations>
		</graphics>
		<graphics preset="medium">
			<textureMaxLoad>2048</textureMaxLoad>
			<aircraftLightsQuality>3</aircraftLightsQuality>
			<aircraftShadows>1</aircraftShadows>
			<aircraftReflections>0</aircraftReflections>
			<cockpitHighRes>1</cockpitHighRes>
			<landingLights>1</landingLights>
			<aircraftSelfShadowEnable>0</aircraftSelfShadowEnable>
			<effectsQuality>2</effectsQuality>
			<groundShadows>0</groundShadows>
			<textureQuality>3</textureQuality>
			<d3d10>0</d3d10>
			<antialiasing>1</antialiasing>
			<anisotropic>1</anisotropic>
			<bilinear>0</bilinear>
			<trilinear>0</trilinear>
			<resolution>1920x1080</resolution>
			<bloom>1</bloom>
			<lensFlare>0</lensFlare>
			<panelsQuality>2</panelsQuality>
			<cloudQuality>2</cloudQuality>
			<cloudDrawDistance>120</cloudDrawDistance>
			<cloudCoverageDensity>70</cloudCoverageDensity>
			<terrainResolution>40</terrainResolution>
			<sceneryDensity>40</sceneryDensity>
			<roadVehicleDensity>40</roadVehicleDensity>
			<boatDensity>40</boatDensity>
			<airlineTrafficDensity>60</airlineTrafficDensity>
			<airportGroundVehiclesDensity>60</airportGroundVehiclesDensity>
			<waterReflections>0</waterReflections>
			<waveRippleEffect>1</waveRippleEffect>
			<advancedAnimations>1</advancedAnimations>
		</graphics>
		<graphics preset="high">
			<textureMaxLoad>2048</textureMaxLoad>
			<aircraftLightsQuality>4</aircraftLightsQuality>
			<aircraftShadows>1</aircraftShadows>
			<aircraftReflections>1</aircraftReflections>
			<cockpitHighRes>1</cockpitHighRes>
			<landingLights>1</landingLights>
			<aircraftSelfShadowEnable>1</aircraftSelfShadowEnable>
			<effectsQuality>3</effectsQuality>
			<groundShadows>0</groundShadows>
			<textureQuality>4</textureQuality>
			<d3d10>1</d3d10>
			<antialiasing>1</antialiasing>
			<anisotropic>1</anisotropic>
			<bilinear>0</bilinear>
			<trilinear>0</trilinear>
			<resolution>1920x1080</resolution>
			<bloom>1</bloom>
			<lensFlare>1</lensFlare>
			<panelsQuality>3</panelsQuality>
			<cloudQuality>2</cloudQuality>
			<cloudDrawDistance>200</cloudDrawDistance>
			<cloudCoverageDensity>90</cloudCoverageDensity>
			<terrainResolution>70</terrainResolution>
			<sceneryDensity>70</sceneryDensity>
			<roadVehicleDensity>80</roadVehicleDensity>
			<boatDensity>80</boatDensity>
			<airlineTrafficDensity>80</airlineTrafficDensity>
			<airportGroundVehiclesDensity>80</airportGroundVehiclesDensity>
			<waterReflections>1</waterReflections>
			<waveRippleEffect>1</waveRippleEffect>
			<advancedAnimations>1</advancedAnimations>
		</graphics>
		<graphics preset="ultra_high">
			<textureMaxLoad>4096</textureMaxLoad>
			<aircraftLightsQuality>5</aircraftLightsQuality>
			<aircraftShadows>1</aircraftShadows>
			<aircraftReflections>1</aircraftReflections>
			<cockpitHighRes>1</cockpitHighRes>
			<landingLights>1</landingLights>
			<aircraftSelfShadowEnable>1</aircraftSelfShadowEnable>
			<effectsQuality>4</effectsQuality>
			<groundShadows>1</groundShadows>
			<textureQuality>4</textureQuality>
			<d3d10>1</d3d10>
			<antialiasing>1</antialiasing>
			<anisotropic>1</anisotropic>
			<bilinear>0</bilinear>
			<trilinear>0</trilinear>
			<resolution>1920x1080</resolution>
			<bloom>1</bloom>
			<lensFlare>1</lensFlare>
			<panelsQuality>3</panelsQuality>
			<cloudQuality>3</cloudQuality>
			<cloudDrawDistance>300</cloudDrawDistance>
			<cloudCoverageDensity>100</cloudCoverageDensity>
			<terrainResolution>100</terrainResolution>
			<sceneryDensity>100</sceneryDensity>
			<roadVehicleDensity>100</roadVehicleDensity>
			<boatDensity>100</boatDensity>
			<airlineTrafficDensity>100</airlineTrafficDensity>
			<airportGroundVehiclesDensity>100</airportGroundVehiclesDensity>
			<waterReflections>1</waterReflections>
			<waveRippleEffect>1</waveRippleEffect>
			<advancedAnimations>1</advancedAnimations>
		</graphics>
		<realism preset="easy">
			<realismLevel>beginner</realismLevel>
			<crashesAllow>0</crashesAllow>
			<aircraftStressAllow>0</aircraftStressAllow>
			<overspeedAllow>0</overspeedAllow>
			<collisionsAllow>0</collisionsAllow>
			<automaticMixtureEnable>1</automaticMixtureEnable>
			<autoTrim>1</autoTrim>
			<failureManagerEnable>1</failureManagerEnable>
			<randomFailureEnable>1</randomFailureEnable>
		</realism>
		<realism preset="medium">
			<realismLevel>advanced</realismLevel>
			<crashesAllow>1</crashesAllow>
			<aircraftStressAllow>0</aircraftStressAllow>
			<overspeedAllow>0</overspeedAllow>
			<collisionsAllow>1</collisionsAllow>
			<automaticMixtureEnable>1</automaticMixtureEnable>
			<autoTrim>0</autoTrim>
			<failureManagerEnable>1</failureManagerEnable>
			<randomFailureEnable>1</randomFailureEnable>
		</realism>
		<realism preset="hard">
			<realismLevel>professional</realismLevel>
			<crashesAllow>1</crashesAllow>
			<aircraftStressAllow>1</aircraftStressAllow>
			<overspeedAllow>1</overspeedAllow>
			<collisionsAllow>1</collisionsAllow>
			<automaticMixtureEnable>0</automaticMixtureEnable>
			<autoTrim>0</autoTrim>
			<failureManagerEnable>1</failureManagerEnable>
